spring.application.name=SistemaRecomendaciones
spring.datasource.url=jdbc:postgresql://localhost:5432/SRUser
spring.datasource.username=postgres
spring.datasource.password=2805
spring.jpa.hibernate.ddl-auto=update

key.signature=74gjiudJSm411s9lkwlHO/LPh7qU0n48IxLYMpqV2sw=

