spring.application.name=SRRestaurant
spring.datasource.url=jdbc:postgresql://localhost:5432/SRRestaurant
spring.datasource.username=postgres
spring.datasource.password=2805
spring.jpa.hibernate.ddl-auto=update
